apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: literary-llama-python 
  janus-idp.io/tekton: literary-llama-python
  backstage.io/kubernetes-id: literary-llama-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: literary-llama-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  