apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: literary-llama-python
  janus-idp.io/tekton: literary-llama-python
  backstage.io/kubernetes-id: literary-llama-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: literary-llama-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
