apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: literary-llama-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: literary-llama-python 
  name: literary-llama-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: literary-llama-python 
